<?php
declare(strict_types=1);
final class AdminPerfumeService {
    public function __construct(private PDO $db,private PerfumeRepository $repo,private AuditService $audit){}
    private function clean(array $input):array{$v=new PerfumeValidator();$check=$v->validate($input);if($check['errors'])throw new InvalidArgumentException(implode(' ',$check['errors']));$slug=$check['data']['slug'];$id=isset($input['_id'])?(int)$input['_id']:null;if($this->repo->slugExists($slug,$id))throw new InvalidArgumentException('El slug ya está en uso.');$status=$input['status']??'borrador';$data=['brand_id'=>!empty($input['brand_id'])?(int)$input['brand_id']:null,'category_id'=>!empty($input['category_id'])?(int)$input['category_id']:null,'olfactory_family_id'=>!empty($input['olfactory_family_id'])?(int)$input['olfactory_family_id']:null,'name'=>$check['data']['name'],'slug'=>$slug,'subtitle'=>trim((string)($input['subtitle']??''))?:null,'short_description'=>trim((string)($input['short_description']??''))?:null,'full_description'=>$this->sanitize((string)($input['full_description']??''))?:null,'gender'=>$input['gender']??'no_aplica','concentration'=>$input['concentration']??'otro','launch_year'=>($input['launch_year']??'')!==''?(int)$input['launch_year']:null,'perfumer'=>trim((string)($input['perfumer']??''))?:null,'origin_country'=>trim((string)($input['origin_country']??''))?:null,'main_image'=>'assets/images/placeholders/perfume.svg','availability_status'=>$input['availability_status']??'pendiente','status'=>in_array($status,PerfumeValidator::STATUSES,true)?$status:'borrador','is_published'=>0,'is_featured'=>!empty($input['is_featured'])?1:0,'is_new'=>!empty($input['is_new'])?1:0,'is_bestseller'=>!empty($input['is_bestseller'])?1:0,'is_promotion'=>!empty($input['is_promotion'])?1:0,'show_price'=>!empty($input['show_price'])?1:0,'price_from'=>($input['price_from']??'')!==''?(float)$input['price_from']:null,'price_text'=>trim((string)($input['price_text']??''))?:null,'whatsapp_message'=>trim((string)($input['whatsapp_message']??''))?:null,'season'=>trim((string)($input['season']??''))?:null,'occasion'=>trim((string)($input['occasion']??''))?:null,'intensity'=>trim((string)($input['intensity']??''))?:null,'longevity'=>trim((string)($input['longevity']??''))?:null,'sillage'=>trim((string)($input['sillage']??''))?:null,'audience'=>trim((string)($input['audience']??''))?:null,'sort_order'=>max(0,(int)($input['sort_order']??0)),'meta_title'=>trim((string)($input['meta_title']??''))?:null,'meta_description'=>trim((string)($input['meta_description']??''))?:null,'og_title'=>trim((string)($input['og_title']??''))?:null,'og_description'=>trim((string)($input['og_description']??''))?:null,'og_image'=>trim((string)($input['og_image']??''))?:null,'robots'=>$input['robots']??'index,follow','canonical_url'=>trim((string)($input['canonical_url']??''))?:null];return $data;}
    private function sanitize(string $html):string{$html=preg_replace('/<\/?(script|iframe|form|input|style|object|embed)[^>]*>/i','',$html)??'';$html=preg_replace('/\s+on[a-z]+\s*=\s*("[^"]*"|\'[^\']*\'|[^\s>]+)/i','',$html)??'';return preg_replace('/javascript\s*:/i','',$html)??'';}
    public function save(array $input,?int $id=null):int{$this->db->beginTransaction();try{$input['_id']=$id;$data=$this->clean($input);$old=$id?$this->repo->adminFind($id):null;if($old)$data['main_image']=$old['main_image']?:'assets/images/placeholders/perfume.svg';if($id&&$old&&$old['slug']!==$data['slug'])$this->repo->addAlias($id,$old['slug']);$saved=$this->repo->adminSave($data,$id);$cats=(array)($input['categories']??[]);if(!empty($data['category_id']))array_unshift($cats,(int)$data['category_id']);$this->repo->replaceCategories($saved,$cats,(int)($input['category_id']??0));$this->repo->replaceTags($saved,(array)($input['tags']??[]));$this->audit->record($id?'perfume_updated':'perfume_created','perfume',$saved,['name'=>$data['name']]);$this->db->commit();return $saved;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();error_log('Admin perfume save error: '.$e->getMessage());throw $e;}}
    public function publish(int $id):void{$p=$this->repo->adminFind($id);if(!$p)throw new InvalidArgumentException('Perfume no encontrado.');$errors=(new PerfumeValidator())->publicationErrors($p,$this->repo);if($errors)throw new InvalidArgumentException('No se puede publicar todavía: '.implode(' ',$errors));$this->db->beginTransaction();try{$this->repo->setState($id,'publicado',true,$p['published_at']??date('Y-m-d H:i:s'));$this->audit->record('perfume_published','perfume',$id);$this->db->commit();}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
    public function state(int $id,string $state):void{$allowed=['despublicar'=>['borrador',false,null],'archivar'=>['archivado',false,null],'restaurar'=>['borrador',false,null]];if(!isset($allowed[$state]))throw new InvalidArgumentException('Acción no válida.');if(!$this->repo->adminFind($id))throw new InvalidArgumentException('Perfume no encontrado.');$this->db->beginTransaction();try{$this->repo->setState($id,...$allowed[$state]);$this->audit->record('perfume_'.$state,'perfume',$id);$this->db->commit();}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
    public function softDelete(int $id):void{$this->db->beginTransaction();try{$this->repo->softDelete($id);$this->audit->record('perfume_deleted','perfume',$id);$this->db->commit();}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
    public function duplicate(int $id):int{$p=$this->repo->adminFind($id,false);if(!$p)throw new InvalidArgumentException('Perfume no encontrado.');$p['name'].=' (copia)';$p['slug']=$p['slug'].'-copia';$p['status']='borrador';$p['is_published']=0;unset($p['id'],$p['created_at'],$p['updated_at'],$p['deleted_at'],$p['brand_name'],$p['category_name'],$p['family_name']);return $this->save($p);}
}
