<?php
declare(strict_types=1);
class AdminTaxonomyService{
 public function __construct(private PDO $db,private TaxonomyRepository $repo,private string $type,private AuditService $audit){}
 private function normalizedFields(array $input):array{$data=TaxonomyValidator::data($input,$this->type);if($this->repo->slugExists($data['slug'],isset($input['_id'])?(int)$input['_id']:null))throw new InvalidArgumentException('El slug ya está en uso.');$fields=$data;foreach(['description','website_url','country','logo','image','icon','note_group','category_type','meta_title','meta_description','parent_id','is_active','is_featured','sort_order']as$key)if(array_key_exists($key,$input)){$value=$input[$key];$fields[$key]=is_string($value)&&trim($value)===''?null:$value;}if($this->type==='category')$this->validateParent($fields['parent_id']??null,isset($input['_id'])?(int)$input['_id']:null);return$fields;}
 private function validateParent(mixed$parent,?int$id):void{if(!$parent)return;$parent=(int)$parent;if($id&&$parent===$id)throw new InvalidArgumentException('Una categoría no puede ser su propio padre.');$seen=[];$depth=0;while($parent&&$depth++<Env::int('CATEGORY_MAX_DEPTH',3)){$row=$this->db->prepare('SELECT parent_id FROM categories WHERE id=?');$row->execute([$parent]);$next=$row->fetchColumn();if($next===false)break;if($id&&(int)$next===$id)throw new InvalidArgumentException('No se puede crear un ciclo jerárquico.');$parent=(int)$next;}if($depth>Env::int('CATEGORY_MAX_DEPTH',3))throw new InvalidArgumentException('La categoría supera la profundidad máxima.');}
 public function save(array$input,?int$id=null):int{$input['_id']=$id;$saved=$this->repo->save($this->normalizedFields($input),$id);$this->audit->record($id?'taxonomy_updated':'taxonomy_created',$this->type,$saved);return$saved;}
 public function active(int$id,bool$value):void{$this->repo->setActive($id,$value);$this->audit->record($value?'taxonomy_activated':'taxonomy_deactivated',$this->type,$id);}
 public function delete(int$id):void{if($this->repo->dependencyCount($id)>0)throw new InvalidArgumentException('No se puede eliminar: existen perfumes relacionados.');$this->repo->softDelete($id);$this->audit->record('taxonomy_deleted',$this->type,$id);}
 public function restore(int$id):void{$this->repo->restore($id);$this->audit->record('taxonomy_restored',$this->type,$id);}
 public function deleteForever(int$id):void{if($this->repo->dependencyCount($id)>0)throw new InvalidArgumentException('No se puede eliminar definitivamente mientras existan dependencias.');$this->repo->deleteForever($id);$this->audit->record('taxonomy_deleted_forever',$this->type,$id);}
 public function merge(int$source,int$target):void{$this->db->beginTransaction();try{$this->repo->merge($source,$target);$this->audit->record('taxonomy_merged',$this->type,$target,['source'=>$source]);$this->db->commit();}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
}
