<?php
declare(strict_types=1);
final class ImportService{
 private AuditService $audit;
 public function __construct(private PDO $db){$this->audit=new AuditService($db);}
 public function create(string $type,array $file):int{$s=$this->db->prepare('INSERT INTO imports(type,original_filename,stored_filename,file_path,mime_type,file_size,file_hash,status) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$type,$file['name'],$file['stored'],$file['path'],$file['mime'],$file['size'],$file['hash'],'subido']);return(int)$this->db->lastInsertId();}
 public function validate(int $id):array{$s=$this->db->prepare('SELECT * FROM imports WHERE id=? AND deleted_at IS NULL');$s->execute([$id]);$imp=$s->fetch();if(!$imp)throw new InvalidArgumentException('Importación no encontrada.');$rows=(new ImportValidationService())->rows($imp['file_path'],$imp['type']);$this->db->beginTransaction();try{$this->db->prepare('DELETE FROM import_rows WHERE import_id=?')->execute([$id]);$ins=$this->db->prepare('INSERT INTO import_rows(import_id,row_number,raw_data_json,status,errors_json) VALUES(?,?,?,?,?)');$errors=0;foreach($rows as $row){if($row['status']==='error')$errors++;$ins->execute([$id,$row['row_number'],json_encode($row['raw'],JSON_UNESCAPED_UNICODE),$row['status'],json_encode($row['errors'],JSON_UNESCAPED_UNICODE)]);}$status=$errors?'con_errores':'validado';$this->db->prepare('UPDATE imports SET status=?,total_rows=?,valid_rows=?,error_rows=?,summary_json=? WHERE id=?')->execute([$status,count($rows),count($rows)-$errors,$errors,json_encode(['simulation'=>true],JSON_UNESCAPED_UNICODE),$id]);$this->db->commit();$this->audit->record('import_validated','import',$id,['rows'=>count($rows),'errors'=>$errors]);return['total'=>count($rows),'errors'=>$errors,'status'=>$status];}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
 public function confirm(int $id,string $confirmation):void{if($confirmation!=='IMPORTAR')throw new InvalidArgumentException('Debes escribir IMPORTAR para confirmar.');$s=$this->db->prepare("UPDATE imports SET status='listo' WHERE id=? AND status='validado' AND error_rows=0");$s->execute([$id]);if($s->rowCount()!==1)throw new InvalidArgumentException('La importación debe estar validada y sin errores.');$this->audit->record('import_confirmed','import',$id);}
}
