<?php
declare(strict_types=1);
final class PerfumeValidator {
    public const STATUSES=['borrador','pendiente_revision','publicado','archivado'];
    public const AVAILABILITY=['disponible','pocas_unidades','agotado','por_pedido','pendiente','descontinuado'];
    public const GENDERS=['mujer','hombre','unisex','infantil','no_aplica'];
    public const CONCENTRATIONS=['parfum','extracto','eau_de_parfum','eau_de_toilette','eau_de_cologne','eau_fraiche','body_mist','aceite','otro'];
    public function validate(array $input,?array $current=null): array {$errors=[];$name=trim((string)($input['name']??''));if($name===''||mb_strlen($name)>200)$errors['name']='El nombre es obligatorio y debe tener máximo 200 caracteres.';$slug=SlugService::make((string)($input['slug']??$name));if($slug===''||!Validator::slug($slug))$errors['slug']='El slug no es válido.';if(!in_array((string)($input['gender']??'no_aplica'),self::GENDERS,true))$errors['gender']='El género seleccionado no es válido.';if(!in_array((string)($input['concentration']??'otro'),self::CONCENTRATIONS,true))$errors['concentration']='La concentración seleccionada no es válida.';if(!in_array((string)($input['availability_status']??'pendiente'),self::AVAILABILITY,true))$errors['availability_status']='La disponibilidad no es válida.';$year=$input['launch_year']??'';if($year!==''&&(!ctype_digit((string)$year)||(int)$year<1800||(int)$year>date('Y')+1))$errors['launch_year']='El año de lanzamiento no es válido.';if(($input['price_from']??'')!==''&&(!is_numeric($input['price_from'])||(float)$input['price_from']<0))$errors['price_from']='El precio debe ser un número no negativo.';if(mb_strlen((string)($input['short_description']??''))>1000)$errors['short_description']='La descripción corta es demasiado larga.';if(!in_array((string)($input['robots']??'index,follow'),['index,follow','noindex,follow','noindex,nofollow'],true))$errors['robots']='La directiva robots no es válida.';return ['data'=>['name'=>$name,'slug'=>$slug],'errors'=>$errors];}
    public function publicationErrors(array $perfume,PerfumeRepository $repo): array {$errors=[];if(empty($perfume['name']))$errors[]='Falta el nombre.';if(empty($perfume['slug']))$errors[]='Falta un slug válido.';if(empty($perfume['brand_id']))$errors[]='Falta seleccionar una marca activa.';if(empty($perfume['category_id']))$errors[]='Falta una categoría principal.';if(empty($perfume['short_description'])&&empty($perfume['full_description']))$errors[]='Falta una descripción.';if(empty($perfume['availability_status'])||$perfume['availability_status']==='pendiente')$errors[]='Debe definirse la disponibilidad.';if($repo->adminRelations((int)$perfume['id'])['images']===[]&&empty($perfume['main_image']))$errors[]='Falta una imagen o fallback válido.';if(!in_array($perfume['status']??'',self::STATUSES,true)||!empty($perfume['deleted_at']))$errors[]='El registro no puede publicarse en su estado actual.';return $errors;}
}
