<?php
$filters=$filters??[];$options=$options??[];$result=$result??['items'=>[],'total'=>0,'page'=>1,'pages'=>0];$headExtra='<link rel="stylesheet" href="'.asset('css/catalog.css').'">';$active=[];
foreach(['brand'=>'Marca','category'=>'Categoría','gender'=>'Género','family'=>'Familia','concentration'=>'Concentración','availability'=>'Disponibilidad','q'=>'Búsqueda'] as $key=>$label){if(isset($filters[$key]))$active[$key]=$label.': '.(in_array($key,['gender','concentration','availability'],true)?catalog_label($key,$filters[$key]):$filters[$key]);}
ob_start(); ?>
<section class="catalog-hero"><div class="site-container"><p class="eyebrow">COLECCIÓN LES SENS</p><p class="breadcrumbs"><a href="<?=url()?>">Inicio</a> / Catálogo</p><h1>Catálogo de fragancias</h1><p>Explora fragancias publicadas y consulta disponibilidad directamente con Les Sens.</p></div></section>
<section class="catalog-section"><div class="site-container"><div class="catalog-toolbar"><div><p class="eyebrow">EXPLORA A TU MANERA</p><h2><?= (int)$result['total'] ?> <?= $result['total']===1?'fragancia encontrada':'fragancias encontradas' ?></h2></div><button class="filter-mobile-button" type="button" data-catalog-filters>Filtrar resultados</button></div>
<?php if($active){ ?><div class="filter-chips"><?php foreach($active as $key=>$label){$clean=$filters;unset($clean[$key]); ?><a class="filter-chip" href="<?=build_query_url('catalogo',$clean)?>"><?=e($label)?> ×</a><?php } ?><a class="clear-filters" href="<?=url('catalogo')?>">Limpiar filtros</a></div><?php } ?>
<div class="catalog-layout"><aside class="catalog-filters" data-filter-panel><h3>Filtrar por</h3><form method="get" action="<?=url('catalogo')?>"><label for="catalog-q">Buscar</label><input id="catalog-q" type="search" name="q" value="<?=e($filters['q']??'')?>" maxlength="100" placeholder="Perfume, marca o estilo">
<?php foreach([['brand','Marca','brands','slug','name'],['category','Categoría','categories','slug','name'],['family','Familia olfativa','families','slug','name'],['gender','Género','genders','value','value'],['concentration','Concentración','concentrations','value','value'],['availability','Disponibilidad','availabilities','value','value'],['tag','Estilo','tags','slug','name']] as [$key,$label,$group,$valueKey,$nameKey]){$items=array_filter($options[$group]??[],fn($item)=>($item['total']??1)>0);if(!$items)continue; ?><label for="filter-<?=e($key)?>"><?=e($label)?><select id="filter-<?=e($key)?>" name="<?=e($key)?>"><option value="">Todas</option><?php foreach($items as $item){$value=$item[$valueKey];$name=$nameKey==='value'?catalog_label($key,$item[$nameKey]):$item[$nameKey]; ?><option value="<?=e($value)?>" <?= (($filters[$key]??'')===$value)?'selected':'' ?>><?=e($name)?></option><?php } ?></select></label><?php } ?>
<?php foreach(['featured'=>'Destacadas','new'=>'Nuevas','promotion'=>'En promoción'] as $key=>$label){ ?><label><input type="checkbox" name="<?=e($key)?>" value="1" <?= (($filters[$key]??'')==='1')?'checked':'' ?>> <?=e($label)?></label><?php } ?><button class="button button-dark" type="submit">Aplicar filtros</button></form></aside>
<div class="catalog-results"><div class="results-sort"><span>Opciones publicadas</span><form method="get" action="<?=url('catalogo')?>"><input type="hidden" name="q" value="<?=e($filters['q']??'')?>"><label for="sort">Ordenar <select id="sort" name="sort"><option value="relevance">Relevancia</option><option value="name_asc" <?= (($filters['sort']??'')==='name_asc')?'selected':'' ?>>Nombre A-Z</option><option value="name_desc" <?= (($filters['sort']??'')==='name_desc')?'selected':'' ?>>Nombre Z-A</option><option value="newest" <?= (($filters['sort']??'')==='newest')?'selected':'' ?>>Más recientes</option></select></label><button type="submit">Aplicar</button></form></div>
<?php if(!empty($result['database_error'])){ ?><div class="catalog-empty"><h3>El catálogo no está disponible temporalmente</h3><a class="button button-dark" href="<?=whatsapp_href()?>">Consultar por WhatsApp</a></div><?php }elseif($result['items']){ ?><div class="catalog-grid"><?php foreach($result['items'] as $perfume)require dirname(__DIR__).'/partials/perfume-card.php'; ?></div><?php }else{ ?><div class="catalog-empty"><span aria-hidden="true">✦</span><h3><?=$active?'No encontramos fragancias con esa combinación':'Estamos preparando nuestra selección'?></h3><p>Escríbenos y te ayudaremos a encontrar una opción según tus gustos.</p><a class="button button-dark" href="<?=whatsapp_href()?>">Consultar por WhatsApp</a></div><?php } ?>
<?php if(($result['pages']??0)>1){ ?><nav class="pagination" aria-label="Paginación"><?php for($n=1;$n<=$result['pages'];$n++){$params=$filters;$params['page']=$n; ?><a class="<?=$n===$result['page']?'current':''?>" href="<?=build_query_url('catalogo',$params)?>"><?=$n?></a><?php } ?></nav><?php } ?></div></div></div></section>
<?php $content=ob_get_clean();require dirname(__DIR__).'/layouts/main.php';
