<?php
declare(strict_types=1);
final class AdminImportController{
 public function __construct(private PDO$db){$this->repo=new ImportRepository($db);$this->service=new ImportService($db);}private ImportRepository$repo;private ImportService$service;private function csrf():void{if(!verify_csrf())throw new RuntimeException('La sesión expiró.');}private function id(mixed$v):int{$id=filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if(!$id)throw new RuntimeException('ID inválido.');return(int)$id;}
 public function index():string{return view('admin/imports/index',['items'=>$this->repo->all(),'title'=>'Importaciones','section'=>'importaciones']);}public function create():string{return view('admin/imports/create',['title'=>'Nueva importación','section'=>'importaciones']);}
 public function upload():string{try{$this->csrf();$type=(string)($_POST['type']??'perfumes');$file=(new ImportFileService())->store($_FILES['file']??[]);$id=$this->service->create($type,$file);$this->service->validate($id);flash('success','Archivo subido y validado en modo simulación.');redirect('admin/importaciones/'.$id);}catch(Throwable$e){flash('error',$e->getMessage());redirect('admin/importaciones/nueva');}}
 public function show(mixed$raw):string{$id=$this->id($raw);$imp=$this->repo->find($id);if(!$imp){http_response_code(404);return view('errors/404');}$rows=(new ImportRowRepository($this->db))->rows($id);return view('admin/imports/show',['import'=>$imp,'rows'=>$rows,'title'=>'Importación #'.$id,'section'=>'importaciones']);}
 public function confirm(mixed$raw):string{$id=$this->id($raw);try{$this->csrf();$this->service->confirm($id,(string)($_POST['confirmation']??''));flash('success','Importación preparada para procesamiento; no se publicó ningún perfume.');}catch(Throwable$e){flash('error',$e->getMessage());}redirect('admin/importaciones/'.$id);}
 public function template(string$type):never{$headers=$type==='perfumes'?['external_id','name','slug','brand','brand_slug','primary_category','gender','concentration','olfactory_family','short_description','full_description','availability_status','show_price','price_from','price_text','launch_year','perfumer','country_of_origin','season','occasion','intensity','longevity','sillage','tags','top_notes','heart_notes','base_notes','general_notes','presentations','is_featured','is_new','sort_order','meta_title','meta_description','status']:['name','slug','description','is_active','sort_order'];header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="plantilla_'.$type.'.csv"');$h=fopen('php://output','wb');fwrite($h,"\xEF\xBB\xBF");fputcsv($h,$headers);exit;}
}
