<?php
declare(strict_types=1);
class AdminContentController{
 private ContentRepository$repo;private array$meta=['promotion'=>['slug'=>'promociones','title'=>'Promociones'],'banner'=>['slug'=>'banners','title'=>'Banners'],'page'=>['slug'=>'paginas','title'=>'Páginas'],'faq'=>['slug'=>'faqs','title'=>'Preguntas frecuentes'],'testimonial'=>['slug'=>'testimonios','title'=>'Testimonios'],'message'=>['slug'=>'mensajes','title'=>'Mensajes'],'social'=>['slug'=>'redes-sociales','title'=>'Redes sociales'],'media'=>['slug'=>'multimedia','title'=>'Biblioteca multimedia']];
 public function __construct(private PDO$db,private string$type){$this->repo=new ContentRepository($db,$type);}
 private function m():array{return$this->meta[$this->type];}private function id(mixed$v):int{$id=filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if(!$id)throw new RuntimeException('Identificador inválido.');return(int)$id;}private function csrf():void{if(!verify_csrf())throw new RuntimeException('La sesión del formulario expiró.');}
 public function index():string{admin_security_headers();$f=[];foreach(['q','active','deleted','sort']as$k)if(isset($_GET[$k])&&!is_array($_GET[$k]))$f[$k]=(string)$_GET[$k];$page=max(1,(int)($_GET['page']??1));$per=min(max(1,Env::int($this->type==='message'?'ADMIN_MESSAGES_PER_PAGE':'ADMIN_CONTENT_PER_PAGE',25)),100);return view('admin/content/index',['result'=>$this->repo->list($f,$page,$per),'filters'=>$f,'type'=>$this->type,'meta'=>$this->m(),'section'=>$this->m()['slug'],'title'=>$this->m()['title']]);}
 public function create():string{return view('admin/content/form',['type'=>$this->type,'meta'=>$this->m(),'taxonomy'=>null,'mode'=>'create','errors'=>flash('admin_errors')?:[],'title'=>'Crear '.$this->m()['title'],'section'=>$this->m()['slug']]);}
 public function store():string{try{$this->csrf();$v=ContentValidator::data($_POST,$this->type);$id=(new AdminContentService($this->db,$this->type))->save($v);flash('success','Contenido creado.');redirect('admin/'.$this->m()['slug'].'/'.$id.'/editar');}catch(Throwable$e){flash('admin_errors',[$e->getMessage()]);return$this->create();}}
 public function edit(mixed$raw):string{$id=$this->id($raw);$row=$this->repo->find($id);if(!$row){http_response_code(404);return view('errors/404');}return view('admin/content/form',['type'=>$this->type,'meta'=>$this->m(),'taxonomy'=>$row,'mode'=>'edit','errors'=>flash('admin_errors')?:[],'title'=>'Editar '.$this->m()['title'],'section'=>$this->m()['slug']]);}
 public function update(mixed$raw):string{$id=$this->id($raw);try{$this->csrf();$v=ContentValidator::data($_POST,$this->type);(new AdminContentService($this->db,$this->type))->save($v,$id);flash('success','Contenido actualizado.');}catch(Throwable$e){flash('error',$e->getMessage());}redirect('admin/'.$this->m()['slug'].'/'.$id.'/editar');}
 public function show(mixed$raw):string{$id=$this->id($raw);$row=$this->repo->find($id);if(!$row){http_response_code(404);return view('errors/404');}return view('admin/content/show',['row'=>$row,'type'=>$this->type,'meta'=>$this->m(),'title'=>$row[$this->type==='faq'?'question':($this->type==='promotion'||$this->type==='page'?'title':'name')]??$this->m()['title'],'section'=>$this->m()['slug']]);}
 public function action(mixed$raw,string$action):string{$id=$this->id($raw);try{$this->csrf();(new AdminContentService($this->db,$this->type))->action($id,$action);flash('success','Acción aplicada.');}catch(Throwable$e){flash('error',$e->getMessage());}redirect('admin/'.$this->m()['slug'].'/'.$id);}
}
