<?php
declare(strict_types=1);
class AdminTaxonomyController{
 private TaxonomyRepository $repo;private AdminTaxonomyService $service;private array $meta=['brand'=>['title'=>'Marcas','slug'=>'marcas','create'=>'Agregar marca'],'category'=>['title'=>'Categorías','slug'=>'categorias','create'=>'Agregar categoría'],'family'=>['title'=>'Familias olfativas','slug'=>'familias-olfativas','create'=>'Agregar familia'],'note'=>['title'=>'Notas olfativas','slug'=>'notas','create'=>'Agregar nota'],'tag'=>['title'=>'Etiquetas','slug'=>'etiquetas','create'=>'Agregar etiqueta']];
 public function __construct(private PDO $db,private string $type){$this->repo=new TaxonomyRepository($db,$type);$this->service=new AdminTaxonomyService($db,$this->repo,$type,new AuditService($db));}
 private function m():array{return$this->meta[$this->type];}private function id(mixed$v):int{$id=filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if(!$id)throw new RuntimeException('Identificador inválido.');return(int)$id;}private function csrf():void{if(!verify_csrf())throw new RuntimeException('La sesión del formulario expiró.');}
 private function data(?array$p=null):array{return['taxonomy'=>$p,'type'=>$this->type,'meta'=>$this->m(),'options'=>$this->type==='category'?$this->repo->options(true):[],'errors'=>flash('admin_errors')?:[]];}
 public function index():string{admin_security_headers();$f=[];foreach(['q','active','deleted','country','parent_id','sort']as$k)if(isset($_GET[$k])&&!is_array($_GET[$k]))$f[$k]=trim((string)$_GET[$k]);$page=max(1,(int)($_GET['page']??1));$per=min(max(1,Env::int('ADMIN_TAXONOMIES_PER_PAGE',25)),max(1,Env::int('ADMIN_TAXONOMIES_MAX_PER_PAGE',100)));return view('admin/taxonomies/index',['result'=>$this->repo->list($f,$page,$per),'filters'=>$f,'type'=>$this->type,'meta'=>$this->m(),'options'=>$this->type==='category'?$this->repo->options(true):[],'section'=>$this->m()['slug'],'title'=>$this->m()['title']]);}
 public function create():string{admin_security_headers();return view('admin/taxonomies/form',array_merge($this->data(),['title'=>$this->m()['create'],'mode'=>'create']));}
 public function store():string{try{$this->csrf();$id=$this->service->save($_POST);flash('success','Registro creado correctamente.');redirect('admin/'.$this->m()['slug'].'/'.$id.'/editar');}catch(Throwable$e){flash('admin_errors',[$e instanceof InvalidArgumentException||$e instanceof RuntimeException?$e->getMessage():'No fue posible guardar el registro.']);return view('admin/taxonomies/form',array_merge($this->data(),['title'=>$this->m()['create'],'mode'=>'create']));}}
 public function show(mixed$raw):string{$id=$this->id($raw);$p=$this->repo->find($id);if(!$p){http_response_code(404);return view('errors/404');}return view('admin/taxonomies/show',['taxonomy'=>$p,'type'=>$this->type,'meta'=>$this->m(),'dependencies'=>$this->repo->dependencyCount($id),'aliases'=>$this->type==='brand'?$this->repo->aliases($id):[],'title'=>$p['name'],'section'=>$this->m()['slug']]);}
 public function edit(mixed$raw):string{$id=$this->id($raw);$p=$this->repo->find($id);if(!$p){http_response_code(404);return view('errors/404');}return view('admin/taxonomies/form',array_merge($this->data($p),['title'=>'Editar '.$this->m()['title'],'mode'=>'edit']));}
 public function update(mixed$raw):string{$id=$this->id($raw);try{$this->csrf();$this->service->save($_POST,$id);flash('success','Registro actualizado.');}catch(Throwable$e){flash('error',$e instanceof InvalidArgumentException||$e instanceof RuntimeException?$e->getMessage():'No fue posible actualizar.');}redirect('admin/'.$this->m()['slug'].'/'.$id.'/editar');}
 public function action(mixed$raw,string$action):string{$id=$this->id($raw);try{$this->csrf();if($action==='activar')$this->service->active($id,true);elseif($action==='desactivar')$this->service->active($id,false);elseif($action==='eliminar')$this->service->delete($id);elseif($action==='restaurar')$this->service->restore($id);elseif($action==='eliminar-definitivamente')$this->service->deleteForever($id);elseif($action==='duplicar'){$p=$this->repo->find($id);$p['name'].=' (copia)';$p['slug'].='-copia';$this->service->save($p);}$action==='fusionar'?$this->service->merge($id,$this->id($_POST['target_id']??0)):null;flash('success','Acción aplicada.');}catch(Throwable$e){flash('error',$e->getMessage());}redirect('admin/'.$this->m()['slug'].'/'.$id);}
 public function alias(mixed$raw):string{$id=$this->id($raw);try{$this->csrf();$this->repo->addAlias($id,trim((string)($_POST['alias']??'')));flash('success','Alias agregado.');}catch(Throwable$e){flash('error','No fue posible agregar el alias.');}redirect('admin/marcas/'.$id);}
 public function aliasDelete(mixed$raw,mixed$alias):string{$id=$this->id($raw);try{$this->csrf();$this->repo->deleteAlias($id,$this->id($alias));flash('success','Alias eliminado.');}catch(Throwable$e){flash('error','No fue posible eliminar el alias.');}redirect('admin/marcas/'.$id);}
 public function media(mixed$raw):string{$id=$this->id($raw);try{$this->csrf();if(empty($_FILES['image']))throw new InvalidArgumentException('Falta seleccionar una imagen.');$path=(new TaxonomyMediaService())->storeTaxonomy($_FILES['image'],$this->type,$id)['path'];$this->repo->save([$this->type==='brand'?'logo':'image'=>$path],$id);flash('success','Imagen guardada.');}catch(Throwable$e){flash('error',$e->getMessage());}redirect('admin/'.$this->m()['slug'].'/'.$id.'/editar');}
 public function mediaDelete(mixed$raw):string{$id=$this->id($raw);try{$this->csrf();$p=$this->repo->find($id);$field=$this->type==='brand'?'logo':'image';if(!empty($p[$field]))(new MediaService())->remove($p[$field]);$this->repo->save([$field=>null],$id);flash('success','Imagen eliminada.');}catch(Throwable$e){flash('error','No fue posible eliminar la imagen.');}redirect('admin/'.$this->m()['slug'].'/'.$id.'/editar');}
}
