<?php
declare(strict_types=1);
final class AdminPerfumeController {
    private PerfumeRepository $repo;private AdminPerfumeService $service;private AuditService $audit;
    public function __construct(private PDO $db){$this->repo=new PerfumeRepository($db);$this->audit=new AuditService($db);$this->service=new AdminPerfumeService($db,$this->repo,$this->audit);}
    private function guardPost(): void {if(!verify_csrf()){http_response_code(419);throw new RuntimeException('La sesión del formulario expiró.');}}
    private function id(mixed $value): int {$id=filter_var($value,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if(!$id)throw new RuntimeException('Identificador inválido.');return (int)$id;}
    private function pageData(?array $perfume=null): array {$relations=$perfume?(new PerfumeRepository($this->db))->adminRelations((int)$perfume['id']):['images'=>[],'presentations'=>[],'notes'=>[],'categories'=>[],'tags'=>[],'aliases'=>[]];return ['perfume'=>$perfume,'relations'=>$relations,'options'=>$this->repo->adminOptions(),'errors'=>flash('admin_errors')?:[],'success'=>flash('success'),'title'=>$perfume?'Editar perfume':'Agregar perfume'];}
    public function index(): string {admin_security_headers();$f=[];foreach(['q','brand','category','status','availability','gender','concentration','sort','featured','new','promotion','images','presentations','deleted'] as $k)if(isset($_GET[$k])&&!is_array($_GET[$k]))$f[$k]=trim((string)$_GET[$k]);$page=max(1,(int)($_GET['page']??1));$per=min(max(1,Env::int('ADMIN_PERFUMES_PER_PAGE',20)),max(1,Env::int('ADMIN_PERFUMES_MAX_PER_PAGE',100)));return view('admin/perfumes/index',['result'=>$this->repo->adminList($f,$page,$per),'filters'=>$f,'options'=>$this->repo->adminOptions(),'title'=>'Perfumes','section'=>'perfumes']);}
    public function create(): string {admin_security_headers();return view('admin/perfumes/create',$this->pageData());}
    public function store(): string {admin_security_headers();try{$this->guardPost();$id=$this->service->save($_POST);$this->upload($id);flash('success','Perfume creado como borrador.');redirect('admin/perfumes/'.$id.'/editar');}catch(Throwable $e){flash('admin_errors',[$e instanceof InvalidArgumentException?$e->getMessage():'No fue posible guardar el perfume.']);return view('admin/perfumes/create',$this->pageData());}}
    public function show(mixed $raw): string {$id=$this->id($raw);$p=$this->repo->adminFind($id);if(!$p){http_response_code(404);return view('errors/404');}return view('admin/perfumes/show',['perfume'=>$p,'relations'=>$this->repo->adminRelations($id),'title'=>$p['name'],'section'=>'perfumes']);}
    public function edit(mixed $raw): string {$id=$this->id($raw);$p=$this->repo->adminFind($id);if(!$p){http_response_code(404);return view('errors/404');}admin_security_headers();return view('admin/perfumes/edit',$this->pageData($p));}
    public function update(mixed $raw): string {$id=$this->id($raw);try{$this->guardPost();$p=$this->repo->adminFind($id);if(!$p)throw new RuntimeException('Perfume no encontrado.');if(!empty($_POST['updated_at'])&&$_POST['updated_at']!==($p['updated_at']??''))throw new RuntimeException('Este perfume fue modificado desde que abriste el formulario.');$saved=$this->service->save($_POST,$id);$this->upload($saved);flash('success','Perfume actualizado correctamente.');redirect('admin/perfumes/'.$id.'/editar');}catch(Throwable $e){flash('admin_errors',[$e instanceof InvalidArgumentException||$e instanceof RuntimeException?$e->getMessage():'No fue posible actualizar el perfume.']);redirect('admin/perfumes/'.$id.'/editar');}}
    public function action(mixed $raw,string $action): string {$id=$this->id($raw);try{$this->guardPost();if($action==='publicar')$this->service->publish($id);elseif($action==='eliminar')$this->service->softDelete($id);elseif($action==='eliminar-definitivamente'){$this->repo->deleteForever($id);$this->audit->record('perfume_deleted_forever','perfume',$id);}else $this->service->state($id,$action);flash('success','Acción aplicada correctamente.');}catch(Throwable $e){flash('error',$e instanceof InvalidArgumentException||$e instanceof RuntimeException?$e->getMessage():'No fue posible aplicar la acción.');}redirect('admin/perfumes/'.$id);}
    public function duplicate(mixed $raw): string {$id=$this->id($raw);try{$this->guardPost();$new=$this->service->duplicate($id);flash('success','Perfume duplicado como borrador.');redirect('admin/perfumes/'.$new.'/editar');}catch(Throwable $e){flash('error','No fue posible duplicar el perfume.');redirect('admin/perfumes/'.$id);}}
    public function preview(mixed $raw): string {$id=$this->id($raw);$p=$this->repo->adminFind($id);if(!$p){http_response_code(404);return view('errors/404');}return view('admin/perfumes/preview',['perfume'=>$p,'relations'=>$this->repo->adminRelations($id),'title'=>'Vista previa: '.$p['name'],'section'=>'perfumes']);}
    private function upload(int $id): void {if(empty($_FILES['image'])||($_FILES['image']['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return;$media=new MediaService();$data=$media->store($_FILES['image'],$id);$data['alt_text']=trim((string)($_POST['image_alt']??''))?:null;$image=$this->repo->addImage($id,$data);if(empty($this->repo->adminRelations($id)['images']))$this->repo->setPrimaryImage($id,$image);$this->audit->record('perfume_image_added','perfume',$id,['image_id'=>$image]);}
    public function images(mixed $raw): string {$id=$this->id($raw);try{$this->guardPost();$this->upload($id);flash('success','Imagen agregada.');}catch(Throwable $e){flash('error',$e instanceof InvalidArgumentException?$e->getMessage():'No fue posible guardar la imagen.');}redirect('admin/perfumes/'.$id.'/editar');}
    public function imageAction(mixed $raw,mixed $imageRaw,string $action): string {$id=$this->id($raw);$imageId=$this->id($imageRaw);try{$this->guardPost();$image=$this->repo->image($id,$imageId);if(!$image)throw new RuntimeException('Imagen no encontrada.');if($action==='principal')$this->repo->setPrimaryImage($id,$imageId);elseif($action==='orden')$this->repo->updateImageOrder($id,$imageId,max(0,(int)($_POST['sort_order']??0)));elseif($action==='eliminar'){$this->repo->deleteImage($id,$imageId);(new MediaService())->remove($image['image_path']);}$this->audit->record('perfume_image_'.$action,'perfume',$id,['image_id'=>$imageId]);flash('success','Imagen actualizada.');}catch(Throwable $e){flash('error','No fue posible actualizar la imagen.');}redirect('admin/perfumes/'.$id.'/editar');}
    public function presentationAction(mixed $raw,?string $presentationRaw=null): string {$id=$this->id($raw);try{$this->guardPost();$d=$_POST;$name=trim((string)($d['name']??''));if($name===''||(!empty($d['size_value'])&&(!is_numeric($d['size_value'])||(float)$d['size_value']<=0))||(!empty($d['price'])&&(!is_numeric($d['price'])||(float)$d['price']<0)))throw new InvalidArgumentException('La presentación tiene datos inválidos.');$pid=$presentationRaw?$this->id($presentationRaw):null;$this->repo->savePresentation($id,$d,$pid);$this->audit->record($pid?'presentation_updated':'presentation_created','perfume',$id);flash('success','Presentación guardada.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect('admin/perfumes/'.$id.'/editar');}
    public function presentationDelete(mixed $raw,mixed $presentationRaw): string {$id=$this->id($raw);try{$this->guardPost();$pid=$this->id($presentationRaw);if(!$this->repo->presentation($id,$pid))throw new RuntimeException();$this->repo->deletePresentation($id,$pid);$this->audit->record('presentation_deleted','perfume',$id,['presentation_id'=>$pid]);flash('success','Presentación eliminada.');}catch(Throwable $e){flash('error','Presentación no encontrada.');}redirect('admin/perfumes/'.$id.'/editar');}
    public function noteAction(mixed $raw): string {$id=$this->id($raw);try{$this->guardPost();$note=$this->id($_POST['note_id']??0);$position=(string)($_POST['note_position']??'general');if(!in_array($position,['salida','corazon','fondo','general'],true))throw new InvalidArgumentException('Posición inválida.');$this->repo->saveNote($id,$note,$position,max(0,(int)($_POST['sort_order']??0)));$this->audit->record('perfume_note_added','perfume',$id,['note_id'=>$note]);flash('success','Nota asociada.');}catch(Throwable $e){flash('error','No fue posible asociar la nota.');}redirect('admin/perfumes/'.$id.'/editar');}
    public function noteDelete(mixed $raw): string {$id=$this->id($raw);try{$this->guardPost();$this->repo->deleteNote($id,$this->id($_POST['note_id']??0),(string)($_POST['note_position']??'general'));$this->audit->record('perfume_note_deleted','perfume',$id);flash('success','Nota eliminada.');}catch(Throwable $e){flash('error','No fue posible eliminar la nota.');}redirect('admin/perfumes/'.$id.'/editar');}
}
