<?php
declare(strict_types=1);
class ContentRepository{
 private array $cfg=['promotion'=>['table'=>'promotions','name'=>'title','fields'=>['title','slug','short_description','full_description','image','mobile_image','promotion_type','status','discount_text','starts_at','ends_at','is_active','is_featured','button_text','button_url','whatsapp_message','sort_order','meta_title','meta_description'],'active'=>'is_active'],'banner'=>['table'=>'banners','name'=>'name','fields'=>['name','title','subtitle','description','desktop_image','mobile_image','button_text','button_url','position','text_alignment','overlay_opacity','starts_at','ends_at','is_active','sort_order'],'active'=>'is_active'],'page'=>['table'=>'pages','name'=>'title','fields'=>['title','slug','excerpt','content','featured_image','status','is_published','published_at','meta_title','meta_description'],'active'=>'is_published'],'faq'=>['table'=>'faqs','name'=>'question','fields'=>['question','answer','category','is_active','sort_order'],'active'=>'is_active'],'testimonial'=>['table'=>'testimonials','name'=>'author_name','fields'=>['author_name','author_avatar','quote','rating','is_verified','consent_obtained','source','is_featured','is_active','sort_order'],'active'=>'is_active'],'message'=>['table'=>'contact_messages','name'=>'name','fields'=>['name','email','phone','subject','message','status','is_read','internal_note'],'active'=>'is_read'],'social'=>['table'=>'social_links','name'=>'platform','fields'=>['platform','label','url','icon','is_active','sort_order'],'active'=>'is_active'],'media'=>['table'=>'media','name'=>'file_name','fields'=>['file_name','path','mime_type','size_bytes','file_hash','alt_text'],'active'=>null]];
 public function __construct(private PDO$db,private string$type){if(!isset($this->cfg[$type]))throw new InvalidArgumentException('Módulo no válido.');}
 private function c():array{return$this->cfg[$this->type];}
 private function columns():array{$s=$this->db->query('SHOW COLUMNS FROM '.$this->c()['table']);return array_column($s->fetchAll(),'Field');}
 public function list(array$f,int$page,int$per):array{$c=$this->c();$cols=$this->columns();$where=['1=1'];$params=[];if(($f['deleted']??'')!=='1'&&in_array('deleted_at',$cols,true))$where[]='x.deleted_at IS NULL';if(!empty($f['q'])){$v='%'.str_replace(['%','_'],['\\%','\\_'],mb_substr(trim((string)$f['q']),0,100)).'%';$name='x.'.$c['name'];$parts=[$name.' LIKE ?'];$params[]=$v;if(in_array('slug',$cols,true)){$parts[]='x.slug LIKE ?';$params[]=$v;}$where[]='('.implode(' OR ',$parts).')';}if(isset($f['active'])&&$c['active']){$where[]='x.'.$c['active'].'=?';$params[]=(int)$f['active'];}$base=' FROM '.$c['table'].' x WHERE '.implode(' AND ',$where);$s=$this->db->prepare('SELECT COUNT(*)'.$base);$s->execute($params);$total=(int)$s->fetchColumn();$orders=['newest'=>'x.created_at DESC','oldest'=>'x.created_at ASC','updated'=>'x.updated_at DESC','name_asc'=>'x.'.$c['name'].' ASC','name_desc'=>'x.'.$c['name'].' DESC','order'=>in_array('sort_order',$cols,true)?'x.sort_order ASC':'x.created_at DESC'];$order=$orders[$f['sort']??'newest']??$orders['newest'];$offset=($page-1)*$per;$s=$this->db->prepare('SELECT x.*'.$base." ORDER BY $order LIMIT $per OFFSET $offset");$s->execute($params);return['items'=>$s->fetchAll(),'total'=>$total,'page'=>$page,'pages'=>$total?(int)ceil($total/$per):0,'per_page'=>$per];}
 public function find(int$id):?array{$s=$this->db->prepare('SELECT * FROM '.$this->c()['table'].' WHERE id=? LIMIT 1');$s->execute([$id]);return$s->fetch()?:null;}
 public function save(array$d,?int$id=null):int{$c=$this->c();$d=array_intersect_key($d,array_flip($c['fields']));if($id){$sets=implode(',',array_map(fn($k)=>"$k=?",array_keys($d)));$s=$this->db->prepare('UPDATE '.$c['table'].' SET '.$sets.' WHERE id=?');$s->execute([...array_values($d),$id]);return$id;}$s=$this->db->prepare('INSERT INTO '.$c['table'].'('.implode(',',array_keys($d)).') VALUES('.implode(',',array_fill(0,count($d),'?')).')');$s->execute(array_values($d));return(int)$this->db->lastInsertId();}
 public function state(int$id,string$state):void{$c=$this->c();$map=['activar'=>[$c['active']=>1],'desactivar'=>[$c['active']=>0],'publicar'=>['status'=>'publicado','is_published'=>1],'despublicar'=>['status'=>'borrador','is_published'=>0],'verificar'=>['is_verified'=>1],'quitar-verificacion'=>['is_verified'=>0],'marcar-leido'=>['is_read'=>1,'status'=>'leido'],'marcar-no-leido'=>['is_read'=>0,'status'=>'nuevo'],'marcar-atendido'=>['status'=>'atendido'],'marcar-pendiente'=>['status'=>'pendiente'],'archivar'=>['status'=>'archivado'],'eliminar'=>['deleted_at'=>date('Y-m-d H:i:s')],'restaurar'=>['deleted_at'=>null]];$fields=$map[$state]??[];$fields=array_intersect_key($fields,array_flip($this->columns()));if(!$fields)throw new InvalidArgumentException('Acción inválida.');$sets=implode(',',array_map(fn($k)=>"$k=?",array_keys($fields)));$s=$this->db->prepare('UPDATE '.$c['table'].' SET '.$sets.' WHERE id=?');$s->execute([...array_values($fields),$id]);}
 public function deleteForever(int$id):void{$this->db->prepare('DELETE FROM '.$this->c()['table'].' WHERE id=?')->execute([$id]);}
}
