<?php
declare(strict_types=1);
final class PerfumeRepository {
    public function __construct(private PDO $db) {}
    private function publicJoins(): string { return " FROM perfumes p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN olfactory_families f ON f.id=p.olfactory_family_id "; }
    private function publicBase(array $filters,&$params): string {
        $where=["p.status='publicado'","p.is_published=1","p.deleted_at IS NULL","(b.id IS NULL OR (b.is_active=1 AND b.deleted_at IS NULL))","(c.id IS NULL OR (c.is_active=1 AND c.deleted_at IS NULL))"];$params=[];
        $add=function(string $sql,mixed $value)use(&$where,&$params):void{$where[]=$sql;$params[]=$value;};
        if(!empty($filters['q'])){foreach(preg_split('/\s+/u',trim((string)$filters['q']))?:[] as $term){if($term==='')continue;$like='%'.$this->escapeLike(mb_substr($term,0,100)).'%';$where[]="(p.name LIKE ? ESCAPE '!' OR b.name LIKE ? ESCAPE '!' OR c.name LIKE ? ESCAPE '!' OR f.name LIKE ? ESCAPE '!' OR EXISTS(SELECT 1 FROM perfume_aliases pa WHERE pa.perfume_id=p.id AND pa.normalized_alias LIKE ? ESCAPE '!') OR EXISTS(SELECT 1 FROM brand_aliases ba WHERE ba.brand_id=b.id AND ba.normalized_alias LIKE ? ESCAPE '!') OR EXISTS(SELECT 1 FROM perfume_tags pt JOIN tags t ON t.id=pt.tag_id WHERE pt.perfume_id=p.id AND t.name LIKE ? ESCAPE '!' AND t.is_active=1 AND t.deleted_at IS NULL))";for($i=0;$i<7;$i++)$params[]=$like;}}
        $maps=['brand'=>'b.slug','category'=>'c.slug','gender'=>'p.gender','family'=>'f.slug','concentration'=>'p.concentration','availability'=>'p.availability_status','season'=>'p.season','occasion'=>'p.occasion','intensity'=>'p.intensity'];
        foreach($maps as $key=>$column)if(!empty($filters[$key])&&is_string($filters[$key]))$add($column.' = ?',$filters[$key]);
        if(!empty($filters['tag'])&&is_string($filters['tag'])){$where[]="EXISTS(SELECT 1 FROM perfume_tags pt2 JOIN tags t2 ON t2.id=pt2.tag_id WHERE pt2.perfume_id=p.id AND t2.slug=?)";$params[]=$filters['tag'];}
        foreach(['featured'=>'is_featured','new'=>'is_new','promotion'=>'is_promotion'] as $key=>$column)if(isset($filters[$key])&&$filters[$key]==='1')$where[]='p.'.$column.'=1';
        return ' WHERE '.implode(' AND ',$where);
    }
    private function escapeLike(string $value): string { return str_replace(['!','%','_'],['!!','!%','!_'],$value); }
    public function paginate(array $filters,int $page,int $perPage): array {
        $params=[];$where=$this->publicBase($filters,$params);$totalStmt=$this->db->prepare('SELECT COUNT(DISTINCT p.id)'.$this->publicJoins().$where);$totalStmt->execute($params);$total=(int)$totalStmt->fetchColumn();
        $sort=['name_asc'=>'p.name ASC','name_desc'=>'p.name DESC','newest'=>'p.created_at DESC','featured'=>'p.is_featured DESC,p.sort_order ASC,p.name ASC','relevance'=>'p.is_featured DESC,p.sort_order ASC,p.name ASC'];$order=$sort[$filters['sort']??'relevance']??$sort['relevance'];$offset=($page-1)*$perPage;
        $sql='SELECT DISTINCT p.*,b.name AS brand_name,b.slug AS brand_slug,c.name AS category_name,c.slug AS category_slug,f.name AS family_name'.$this->publicJoins().$where." ORDER BY {$order} LIMIT {$perPage} OFFSET {$offset}";$stmt=$this->db->prepare($sql);$stmt->execute($params);
        return ['items'=>$stmt->fetchAll(),'total'=>$total,'page'=>$page,'per_page'=>$perPage,'pages'=>$total?ceil($total/$perPage):0];
    }
    public function filterOptions(): array {
        $base=" WHERE p.status='publicado' AND p.is_published=1 AND p.deleted_at IS NULL AND (b.id IS NULL OR (b.is_active=1 AND b.deleted_at IS NULL)) AND (c.id IS NULL OR (c.is_active=1 AND c.deleted_at IS NULL))";
        $brands=$this->db->query("SELECT b.name,b.slug,COUNT(DISTINCT p.id) total FROM perfumes p JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id {$base} GROUP BY b.id ORDER BY b.name")->fetchAll();
        $categories=$this->db->query("SELECT c.name,c.slug,COUNT(DISTINCT p.id) total FROM perfumes p JOIN categories c ON c.id=p.category_id LEFT JOIN brands b ON b.id=p.brand_id {$base} GROUP BY c.id ORDER BY c.sort_order,c.name")->fetchAll();
        $families=$this->db->query("SELECT f.name,f.slug,COUNT(DISTINCT p.id) total FROM perfumes p JOIN olfactory_families f ON f.id=p.olfactory_family_id LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id {$base} GROUP BY f.id ORDER BY f.sort_order,f.name")->fetchAll();
        $tags=$this->db->query("SELECT t.name,t.slug,COUNT(DISTINCT p.id) total FROM perfumes p JOIN perfume_tags pt ON pt.perfume_id=p.id JOIN tags t ON t.id=pt.tag_id LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id {$base} AND t.is_active=1 GROUP BY t.id ORDER BY t.name")->fetchAll();
        return ['brands'=>$brands,'categories'=>$categories,'families'=>$families,'tags'=>$tags,'genders'=>$this->distinct('p.gender',$base),'concentrations'=>$this->distinct('p.concentration',$base),'availabilities'=>$this->distinct('p.availability_status',$base),'seasons'=>$this->distinct('p.season',$base),'occasions'=>$this->distinct('p.occasion',$base),'intensities'=>$this->distinct('p.intensity',$base)];
    }
    private function distinct(string $column,string $base): array { $sql="SELECT DISTINCT {$column} value,COUNT(*) total FROM perfumes p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id {$base} AND {$column} IS NOT NULL AND {$column}<>'' GROUP BY {$column} ORDER BY {$column}";return $this->db->query($sql)->fetchAll(); }
    public function findPublicBySlug(string $slug): ?array { $params=[];$where=$this->publicBase([], $params).' AND p.slug=?';$params[]=$slug;$s=$this->db->prepare('SELECT p.*,b.name brand_name,b.slug brand_slug,b.description brand_description,b.logo brand_logo,b.country brand_country,c.name category_name,c.slug category_slug,c.description category_description,f.name family_name,f.slug family_slug'.$this->publicJoins().$where.' LIMIT 1');$s->execute($params);return $s->fetch()?:null; }
    public function findByAlias(string $alias): ?array { $s=$this->db->prepare("SELECT p.slug FROM perfume_aliases pa JOIN perfumes p ON p.id=pa.perfume_id JOIN brands b ON b.id=p.brand_id WHERE pa.normalized_alias=? AND p.status='publicado' AND p.is_published=1 AND p.deleted_at IS NULL AND b.is_active=1 AND b.deleted_at IS NULL LIMIT 1");$s->execute([$alias]);return $s->fetch()?:null; }
    public function images(int $id): array { $s=$this->db->prepare('SELECT * FROM perfume_images WHERE perfume_id=? ORDER BY is_primary DESC,sort_order,id');$s->execute([$id]);return $s->fetchAll(); }
    public function presentations(int $id): array { $s=$this->db->prepare("SELECT * FROM perfume_presentations WHERE perfume_id=? AND is_active=1 ORDER BY sort_order,id");$s->execute([$id]);return $s->fetchAll(); }
    public function notes(int $id): array { $s=$this->db->prepare("SELECT n.name,n.slug,pn.note_position,pn.sort_order FROM perfume_notes pn JOIN notes n ON n.id=pn.note_id WHERE pn.perfume_id=? AND n.is_active=1 ORDER BY FIELD(pn.note_position,'salida','corazon','fondo','general'),pn.sort_order,n.name");$s->execute([$id]);$out=[];foreach($s->fetchAll() as $row)$out[$row['note_position']][]=$row;return $out; }
    public function tags(int $id): array { $s=$this->db->prepare('SELECT t.* FROM perfume_tags pt JOIN tags t ON t.id=pt.tag_id WHERE pt.perfume_id=? AND t.is_active=1 AND t.deleted_at IS NULL ORDER BY t.name');$s->execute([$id]);return $s->fetchAll(); }
    public function categories(int $id): array { $s=$this->db->prepare('SELECT c.* FROM perfume_categories pc JOIN categories c ON c.id=pc.category_id WHERE pc.perfume_id=? AND c.is_active=1 AND c.deleted_at IS NULL ORDER BY pc.is_primary DESC,pc.sort_order,c.name');$s->execute([$id]);return $s->fetchAll(); }
    public function related(array $perfume,int $limit=4): array { $s=$this->db->prepare("SELECT DISTINCT p.*,b.name brand_name,c.name category_name FROM perfumes p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE p.id<>? AND p.status='publicado' AND p.is_published=1 AND p.deleted_at IS NULL AND (p.brand_id=? OR p.category_id=? OR p.gender=?) AND (b.id IS NULL OR (b.is_active=1 AND b.deleted_at IS NULL)) AND (c.id IS NULL OR (c.is_active=1 AND c.deleted_at IS NULL)) ORDER BY p.is_featured DESC,p.sort_order,p.name LIMIT {$limit}");$s->execute([(int)$perfume['id'],$perfume['brand_id'],$perfume['category_id'],$perfume['gender']]);return $s->fetchAll(); }
    public function incrementViews(int $id): void { $s=$this->db->prepare('UPDATE perfumes SET views_count=views_count+1 WHERE id=? AND status=\'publicado\' AND is_published=1 AND deleted_at IS NULL');$s->execute([$id]); }
    public function publicBrands(): array { return $this->db->query("SELECT b.*,COUNT(DISTINCT p.id) total_perfumes FROM brands b JOIN perfumes p ON p.brand_id=b.id WHERE b.is_active=1 AND b.deleted_at IS NULL AND p.status='publicado' AND p.is_published=1 AND p.deleted_at IS NULL GROUP BY b.id ORDER BY b.is_featured DESC,b.sort_order,b.name")->fetchAll(); }
    public function publicBrand(string $slug): ?array { $s=$this->db->prepare("SELECT b.*,COUNT(DISTINCT p.id) total_perfumes FROM brands b JOIN perfumes p ON p.brand_id=b.id AND p.status='publicado' AND p.is_published=1 AND p.deleted_at IS NULL WHERE b.slug=? AND b.is_active=1 AND b.deleted_at IS NULL GROUP BY b.id");$s->execute([$slug]);return $s->fetch()?:null; }
    public function publicCategories(): array { return $this->db->query("SELECT c.*,COUNT(DISTINCT p.id) total_perfumes FROM categories c LEFT JOIN perfumes p ON p.category_id=c.id AND p.status='publicado' AND p.is_published=1 AND p.deleted_at IS NULL WHERE c.is_active=1 AND c.deleted_at IS NULL GROUP BY c.id ORDER BY c.sort_order,c.name")->fetchAll(); }
    public function publicCategory(string $slug): ?array { $s=$this->db->prepare("SELECT c.*,COUNT(DISTINCT p.id) total_perfumes FROM categories c JOIN perfumes p ON p.category_id=c.id AND p.status='publicado' AND p.is_published=1 AND p.deleted_at IS NULL WHERE c.slug=? AND c.is_active=1 AND c.deleted_at IS NULL GROUP BY c.id");$s->execute([$slug]);return $s->fetch()?:null; }

    public function adminList(array $filters,int $page,int $perPage): array {
        $where=[];$params=[];$includeDeleted=($filters['deleted']??'')==='1';
        if(!$includeDeleted)$where[]='p.deleted_at IS NULL';
        $like=function(string $term): string { return '%'.str_replace(['!','%','_'],['!!','!%','!_'],mb_substr($term,0,100)).'%'; };
        if(!empty($filters['q'])){$v=$like((string)$filters['q']);$where[]="(p.name LIKE ? ESCAPE '!' OR p.slug LIKE ? ESCAPE '!' OR b.name LIKE ? ESCAPE '!' OR EXISTS(SELECT 1 FROM perfume_aliases pa WHERE pa.perfume_id=p.id AND pa.normalized_alias LIKE ? ESCAPE '!') OR EXISTS(SELECT 1 FROM perfume_tags pt JOIN tags t ON t.id=pt.tag_id WHERE pt.perfume_id=p.id AND t.name LIKE ? ESCAPE '!') OR EXISTS(SELECT 1 FROM perfume_categories pc JOIN categories cx ON cx.id=pc.category_id WHERE pc.perfume_id=p.id AND cx.name LIKE ? ESCAPE '!'))";array_push($params,$v,$v,$v,$v,$v,$v);}
        $maps=['brand'=>'p.brand_id','category'=>'p.category_id','status'=>'p.status','availability'=>'p.availability_status','gender'=>'p.gender','concentration'=>'p.concentration'];
        foreach($maps as $k=>$column)if(isset($filters[$k])&&$filters[$k]!==''){$where[]="$column=?";$params[]=$filters[$k];}
        foreach(['featured'=>'is_featured','new'=>'is_new','promotion'=>'is_promotion'] as $k=>$column)if(($filters[$k]??'')==='1')$where[]="p.$column=1";
        if(($filters['images']??'')==='with')$where[]='EXISTS(SELECT 1 FROM perfume_images pi WHERE pi.perfume_id=p.id)';if(($filters['images']??'')==='without')$where[]='NOT EXISTS(SELECT 1 FROM perfume_images pi WHERE pi.perfume_id=p.id)';
        if(($filters['presentations']??'')==='with')$where[]='EXISTS(SELECT 1 FROM perfume_presentations pp WHERE pp.perfume_id=p.id AND pp.is_active=1)';if(($filters['presentations']??'')==='without')$where[]='NOT EXISTS(SELECT 1 FROM perfume_presentations pp WHERE pp.perfume_id=p.id AND pp.is_active=1)';
        $sqlWhere=$where?' WHERE '.implode(' AND ',$where):'';$joins=' FROM perfumes p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id';
        $count=$this->db->prepare('SELECT COUNT(*)'.$joins.$sqlWhere);$count->execute($params);$total=(int)$count->fetchColumn();
        $orders=['newest'=>'p.created_at DESC','oldest'=>'p.created_at ASC','updated'=>'p.updated_at DESC','name_asc'=>'p.name ASC','name_desc'=>'p.name DESC','brand'=>'b.name ASC','status'=>'p.status ASC','published'=>'p.is_published DESC,p.updated_at DESC','draft'=>'p.is_published ASC,p.updated_at DESC','featured'=>'p.is_featured DESC,p.name ASC'];$order=$orders[$filters['sort']??'newest']??$orders['newest'];$offset=($page-1)*$perPage;
        $q=$this->db->prepare('SELECT p.*,b.name brand_name,c.name category_name,(SELECT COUNT(*) FROM perfume_images pi WHERE pi.perfume_id=p.id) image_count,(SELECT COUNT(*) FROM perfume_presentations pp WHERE pp.perfume_id=p.id AND pp.is_active=1) presentation_count,(SELECT COUNT(*) FROM perfume_notes pn WHERE pn.perfume_id=p.id) note_count,(SELECT COUNT(*) FROM perfume_tags pt WHERE pt.perfume_id=p.id) tag_count'.$joins.$sqlWhere." ORDER BY $order LIMIT $perPage OFFSET $offset");$q->execute($params);return ['items'=>$q->fetchAll(),'total'=>$total,'page'=>$page,'per_page'=>$perPage,'pages'=>$total?(int)ceil($total/$perPage):0];
    }
    public function adminFind(int $id,bool $includeDeleted=true): ?array {$s=$this->db->prepare('SELECT p.*,b.name brand_name,c.name category_name,f.name family_name FROM perfumes p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN olfactory_families f ON f.id=p.olfactory_family_id WHERE p.id=?'.($includeDeleted?'':' AND p.deleted_at IS NULL').' LIMIT 1');$s->execute([$id]);return $s->fetch()?:null;}
    public function adminRelations(int $id): array { $out=[];foreach(['images'=>'SELECT * FROM perfume_images WHERE perfume_id=? ORDER BY is_primary DESC,sort_order,id','presentations'=>'SELECT * FROM perfume_presentations WHERE perfume_id=? ORDER BY sort_order,id','notes'=>'SELECT pn.*,n.name note_name FROM perfume_notes pn JOIN notes n ON n.id=pn.note_id WHERE pn.perfume_id=? ORDER BY FIELD(pn.note_position,\'salida\',\'corazon\',\'fondo\',\'general\'),pn.sort_order','categories'=>'SELECT pc.*,c.name category_name FROM perfume_categories pc JOIN categories c ON c.id=pc.category_id WHERE pc.perfume_id=? ORDER BY pc.is_primary DESC,pc.sort_order','tags'=>'SELECT pt.*,t.name tag_name FROM perfume_tags pt JOIN tags t ON t.id=pt.tag_id WHERE pt.perfume_id=? ORDER BY t.name','aliases'=>'SELECT * FROM perfume_aliases WHERE perfume_id=? ORDER BY id'] as $key=>$sql){$s=$this->db->prepare($sql);$s->execute([$id]);$out[$key]=$s->fetchAll();}return $out;}
    public function adminOptions(): array {return ['brands'=>$this->db->query('SELECT id,name,is_active FROM brands WHERE deleted_at IS NULL ORDER BY name')->fetchAll(),'categories'=>$this->db->query('SELECT id,name,parent_id,is_active FROM categories WHERE deleted_at IS NULL ORDER BY sort_order,name')->fetchAll(),'families'=>$this->db->query('SELECT id,name,is_active FROM olfactory_families ORDER BY sort_order,name')->fetchAll(),'notes'=>$this->db->query('SELECT id,name,note_group,is_active FROM notes ORDER BY name')->fetchAll(),'tags'=>$this->db->query('SELECT id,name,is_active FROM tags ORDER BY name')->fetchAll()];}
    public function adminSave(array $data,?int $id=null): int { $allowed=['brand_id','category_id','olfactory_family_id','name','slug','subtitle','short_description','full_description','gender','concentration','launch_year','perfumer','origin_country','main_image','video_url','status','availability_status','is_published','is_featured','is_new','is_bestseller','is_promotion','show_price','price_from','price_text','whatsapp_message','season','occasion','intensity','longevity','sillage','audience','sort_order','meta_title','meta_description','og_title','og_description','og_image','robots','canonical_url'];$data=array_intersect_key($data,array_flip($allowed));$columns=array_keys($data);if($id===null){$sql='INSERT INTO perfumes('.implode(',',$columns).') VALUES('.implode(',',array_fill(0,count($columns),'?')).')';$s=$this->db->prepare($sql);$s->execute(array_values($data));return (int)$this->db->lastInsertId();}$sets=implode(',',array_map(fn($c)=>"$c=?",$columns));$s=$this->db->prepare("UPDATE perfumes SET $sets WHERE id=?");$s->execute([...array_values($data),$id]);return $id;}
    public function setState(int $id,string $status,bool $published,?string $publishedAt=null): void {$s=$this->db->prepare('UPDATE perfumes SET status=?,is_published=?,published_at=? WHERE id=?');$s->execute([$status,$published?1:0,$publishedAt,$id]);}
    public function softDelete(int $id): void {$s=$this->db->prepare("UPDATE perfumes SET deleted_at=NOW(),status='borrador',is_published=0 WHERE id=?");$s->execute([$id]);}
    public function restore(int $id): void {$s=$this->db->prepare("UPDATE perfumes SET deleted_at=NULL,status='borrador',is_published=0,published_at=NULL WHERE id=?");$s->execute([$id]);}
    public function deleteForever(int $id): void {$s=$this->db->prepare('DELETE FROM perfumes WHERE id=?');$s->execute([$id]);}
    public function slugExists(string $slug,?int $ignore=null): bool {$sql='SELECT COUNT(*) FROM perfumes WHERE slug=?'.($ignore?' AND id<>?':'');$s=$this->db->prepare($sql);$s->execute($ignore?[$slug,$ignore]:[$slug]);return (int)$s->fetchColumn()>0;}
    public function addAlias(int $id,string $alias): void {$n=SlugService::normalized($alias);if($n==='')return;$s=$this->db->prepare('INSERT IGNORE INTO perfume_aliases(perfume_id,alias,normalized_alias) VALUES(?,?,?)');$s->execute([$id,$alias,$n]);}
    public function replaceCategories(int $id,array $ids,?int $primary): void {$this->db->prepare('DELETE FROM perfume_categories WHERE perfume_id=?')->execute([$id]);$s=$this->db->prepare('INSERT INTO perfume_categories(perfume_id,category_id,is_primary,sort_order) VALUES(?,?,?,?)');$order=0;foreach(array_unique(array_map('intval',$ids)) as $cat)$s->execute([$id,$cat,$primary===$cat?1:0,$order++]);}
    public function replaceTags(int $id,array $ids): void {$this->db->prepare('DELETE FROM perfume_tags WHERE perfume_id=?')->execute([$id]);$s=$this->db->prepare('INSERT IGNORE INTO perfume_tags(perfume_id,tag_id) VALUES(?,?)');foreach(array_unique(array_map('intval',$ids)) as $tag)$s->execute([$id,$tag]);}
    public function image(int $perfumeId,int $imageId): ?array {$s=$this->db->prepare('SELECT * FROM perfume_images WHERE perfume_id=? AND id=?');$s->execute([$perfumeId,$imageId]);return $s->fetch()?:null;}
    public function addImage(int $perfumeId,array $data): int {$s=$this->db->prepare('INSERT INTO perfume_images(perfume_id,image_path,thumbnail_path,alt_text,caption,sort_order,is_primary) VALUES(?,?,?,?,?,?,?)');$s->execute([$perfumeId,$data['image_path'],$data['thumbnail_path']??null,$data['alt_text']??null,$data['caption']??null,(int)($data['sort_order']??0),(int)($data['is_primary']??0)]);return (int)$this->db->lastInsertId();}
    public function setPrimaryImage(int $perfumeId,int $imageId): void {$this->db->prepare('UPDATE perfume_images SET is_primary=0 WHERE perfume_id=?')->execute([$perfumeId]);$this->db->prepare('UPDATE perfume_images SET is_primary=1 WHERE perfume_id=? AND id=?')->execute([$perfumeId,$imageId]);}
    public function updateImageOrder(int $perfumeId,int $imageId,int $order): void {$this->db->prepare('UPDATE perfume_images SET sort_order=? WHERE perfume_id=? AND id=?')->execute([$order,$perfumeId,$imageId]);}
    public function deleteImage(int $perfumeId,int $imageId): void {$this->db->prepare('DELETE FROM perfume_images WHERE perfume_id=? AND id=?')->execute([$perfumeId,$imageId]);}
    public function presentation(int $perfumeId,int $id): ?array {$s=$this->db->prepare('SELECT * FROM perfume_presentations WHERE perfume_id=? AND id=?');$s->execute([$perfumeId,$id]);return $s->fetch()?:null;}
    public function savePresentation(int $perfumeId,array $d,?int $id=null): int {$data=[$d['name'],($d['size_value']??'')!==''?(float)$d['size_value']:null,$d['size_unit']??null,$d['sku']??null,$d['barcode']??null,($d['price']??'')!==''?(float)$d['price']:null,!empty($d['show_price'])?1:0,$d['availability_status']??'pendiente',!empty($d['is_active'])?1:0,max(0,(int)($d['sort_order']??0))];if($id){$s=$this->db->prepare('UPDATE perfume_presentations SET name=?,size_value=?,size_unit=?,sku=?,barcode=?,price=?,show_price=?,availability_status=?,is_active=?,sort_order=? WHERE perfume_id=? AND id=?');$s->execute([...$data,$perfumeId,$id]);return $id;}$s=$this->db->prepare('INSERT INTO perfume_presentations(name,size_value,size_unit,sku,barcode,price,show_price,availability_status,is_active,sort_order,perfume_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$s->execute([...$data,$perfumeId]);return (int)$this->db->lastInsertId();}
    public function deletePresentation(int $perfumeId,int $id): void {$this->db->prepare('DELETE FROM perfume_presentations WHERE perfume_id=? AND id=?')->execute([$perfumeId,$id]);}
    public function saveNote(int $perfumeId,int $noteId,string $position,int $order=0): void {$s=$this->db->prepare('INSERT INTO perfume_notes(perfume_id,note_id,note_position,sort_order) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE sort_order=VALUES(sort_order)');$s->execute([$perfumeId,$noteId,$position,$order]);}
    public function deleteNote(int $perfumeId,int $noteId,string $position): void {$this->db->prepare('DELETE FROM perfume_notes WHERE perfume_id=? AND note_id=? AND note_position=?')->execute([$perfumeId,$noteId,$position]);}
}
