<?php
declare(strict_types=1);
class TaxonomyRepository {
    private array $cfg=['brand'=>['table'=>'brands','label'=>'marca','has_deleted'=>true,'dep'=>'p.brand_id','fields'=>['name','slug','description','logo','website_url','country','is_featured','is_active','sort_order','meta_title','meta_description']],'category'=>['table'=>'categories','label'=>'categoría','has_deleted'=>true,'dep'=>'p.category_id','fields'=>['name','slug','parent_id','description','image','icon','category_type','is_featured','is_active','sort_order','meta_title','meta_description']],'family'=>['table'=>'olfactory_families','label'=>'familia olfativa','has_deleted'=>true,'dep'=>'p.olfactory_family_id','fields'=>['name','slug','description','icon','is_active','sort_order']],'note'=>['table'=>'notes','label'=>'nota','has_deleted'=>true,'dep'=>'pn.note_id','fields'=>['name','slug','description','image','note_group','is_active']],'tag'=>['table'=>'tags','label'=>'etiqueta','has_deleted'=>true,'dep'=>'pt.tag_id','fields'=>['name','slug','description','is_active']]];
    public function __construct(private PDO $db,private string $type){if(!isset($this->cfg[$type]))throw new InvalidArgumentException('Catálogo no válido.');}
    private function c():array{return $this->cfg[$this->type];}private function activeWhere(string $alias='t'):string{return $this->c()['has_deleted']?"$alias.deleted_at IS NULL":'1=1';}
    public function list(array $f,int $page,int $per):array{$c=$this->c();$where=[$this->activeWhere('t')];$params=[];if(($f['deleted']??'')==='1'&&$c['has_deleted'])$where=['t.deleted_at IS NOT NULL'];if(!empty($f['q'])){$v='%'.str_replace(['!','%','_'],['!!','!%','!_'],mb_substr(trim((string)$f['q']),0,100)).'%';$where[]="(t.name LIKE ? ESCAPE '!' OR t.slug LIKE ? ESCAPE '!' OR t.description LIKE ? ESCAPE '!')";array_push($params,$v,$v,$v);}if(isset($f['active'])&&$f['active']!==''){$where[]='t.is_active=?';$params[]=(int)$f['active'];}if($this->type==='brand'&&!empty($f['country'])){$where[]='t.country=?';$params[]=$f['country'];}if($this->type==='category'&&isset($f['parent_id'])&&$f['parent_id']!==''){$where[]='t.parent_id=?';$params[]=(int)$f['parent_id'];}$join='';$dep=$c['dep'];if(str_contains($dep,'pn.'))$join=' LEFT JOIN perfume_notes pn ON pn.note_id=t.id';elseif(str_contains($dep,'pt.'))$join=' LEFT JOIN perfume_tags pt ON pt.tag_id=t.id';else $join=' LEFT JOIN perfumes p ON '.$dep.'=t.id AND p.deleted_at IS NULL';$base=' FROM '.$c['table'].' t'.$join.' WHERE '.implode(' AND ',$where);$count=$this->db->prepare('SELECT COUNT(DISTINCT t.id)'.$base);$count->execute($params);$total=(int)$count->fetchColumn();$orders=['newest'=>'t.created_at DESC','oldest'=>'t.created_at ASC','updated'=>'t.updated_at DESC','name_asc'=>'t.name ASC','name_desc'=>'t.name DESC','used'=>'related_count DESC','active'=>'t.is_active DESC','inactive'=>'t.is_active ASC','order'=>'t.sort_order ASC,t.name ASC'];$order=$orders[$f['sort']??'name_asc']??$orders['name_asc'];$offset=($page-1)*$per;$sql='SELECT t.*,COUNT(DISTINCT '.($this->type==='note'?'pn.perfume_id':($this->type==='tag'?'pt.perfume_id':'p.id')).') related_count'.$base." GROUP BY t.id ORDER BY $order LIMIT $per OFFSET $offset";$s=$this->db->prepare($sql);$s->execute($params);return ['items'=>$s->fetchAll(),'total'=>$total,'page'=>$page,'per_page'=>$per,'pages'=>$total?(int)ceil($total/$per):0];}
    public function find(int $id,bool $includeDeleted=true):?array{$c=$this->c();$s=$this->db->prepare('SELECT * FROM '.$c['table'].' WHERE id=?'.(!$includeDeleted&&$c['has_deleted']?' AND deleted_at IS NULL':'').' LIMIT 1');$s->execute([$id]);return $s->fetch()?:null;}
    public function options(bool $includeDeleted=false):array{$c=$this->c();$sql='SELECT id,name,is_active'.($this->type==='category'?',parent_id':'').' FROM '.$c['table'].($includeDeleted||!$c['has_deleted']?'':' WHERE deleted_at IS NULL').' ORDER BY name';return $this->db->query($sql)->fetchAll();}
    public function save(array $d,?int $id=null):int{$c=$this->c();$d=array_intersect_key($d,array_flip($c['fields']));if($id){$sets=implode(',',array_map(fn($k)=>"$k=?",array_keys($d)));$s=$this->db->prepare('UPDATE '.$c['table'].' SET '.$sets.' WHERE id=?');$s->execute([...array_values($d),$id]);return $id;}$cols=implode(',',array_keys($d));$s=$this->db->prepare('INSERT INTO '.$c['table'].'('.$cols.') VALUES('.implode(',',array_fill(0,count($d),'?')).')');$s->execute(array_values($d));return(int)$this->db->lastInsertId();}
    public function slugExists(string $slug,?int $id=null):bool{$c=$this->c();$s=$this->db->prepare('SELECT COUNT(*) FROM '.$c['table'].' WHERE slug=?'.($id?' AND id<>?':'').' AND '.($c['has_deleted']?'(deleted_at IS NULL OR deleted_at IS NOT NULL)':'1=1'));$s->execute($id?[$slug,$id]:[$slug]);return(int)$s->fetchColumn()>0;}
    public function setActive(int $id,bool $active):void{$s=$this->db->prepare('UPDATE '.$this->c()['table'].' SET is_active=? WHERE id=?');$s->execute([$active?1:0,$id]);}
    public function softDelete(int $id):void{$c=$this->c();if($c['has_deleted'])$this->db->prepare('UPDATE '.$c['table'].' SET deleted_at=NOW(),is_active=0 WHERE id=?')->execute([$id]);else $this->setActive($id,false);}
    public function restore(int $id):void{$c=$this->c();if($c['has_deleted'])$this->db->prepare('UPDATE '.$c['table'].' SET deleted_at=NULL,is_active=0 WHERE id=?')->execute([$id]);else $this->setActive($id,false);}
    public function dependencyCount(int $id):int{$c=$this->c();$dep=$c['dep'];if($this->type==='note')$q='SELECT COUNT(DISTINCT perfume_id) FROM perfume_notes WHERE note_id=?';elseif($this->type==='tag')$q='SELECT COUNT(DISTINCT perfume_id) FROM perfume_tags WHERE tag_id=?';else $q='SELECT COUNT(*) FROM perfumes WHERE '.$dep.'=? AND deleted_at IS NULL';$s=$this->db->prepare($q);$s->execute([$id]);return(int)$s->fetchColumn();}
    public function deleteForever(int $id):void{$this->db->prepare('DELETE FROM '.$this->c()['table'].' WHERE id=?')->execute([$id]);}
    public function aliases(int $id):array{$s=$this->db->prepare('SELECT * FROM brand_aliases WHERE brand_id=? ORDER BY alias');$s->execute([$id]);return$s->fetchAll();}
    public function addAlias(int $id,string $alias):void{$n=SlugService::normalized($alias);if($n==='')throw new InvalidArgumentException('Alias inválido.');$s=$this->db->prepare('INSERT INTO brand_aliases(brand_id,alias,normalized_alias) VALUES(?,?,?)');$s->execute([$id,$alias,$n]);}
    public function deleteAlias(int $id,int $aliasId):void{$this->db->prepare('DELETE FROM brand_aliases WHERE brand_id=? AND id=?')->execute([$id,$aliasId]);}
    public function merge(int $source,int $target):void{$c=$this->c();if($source===$target)throw new InvalidArgumentException('No puedes fusionar un registro consigo mismo.');if($this->type==='brand'){$this->db->prepare('UPDATE perfumes SET brand_id=? WHERE brand_id=?')->execute([$target,$source]);$this->db->prepare('UPDATE brand_aliases SET brand_id=? WHERE brand_id=?')->execute([$target,$source]);}elseif($this->type==='category'){$this->db->prepare('UPDATE perfumes SET category_id=? WHERE category_id=?')->execute([$target,$source]);$this->db->prepare('UPDATE IGNORE perfume_categories SET category_id=? WHERE category_id=?')->execute([$target,$source]);}elseif($this->type==='family')$this->db->prepare('UPDATE perfumes SET olfactory_family_id=? WHERE olfactory_family_id=?')->execute([$target,$source]);elseif($this->type==='note'){$this->db->prepare('UPDATE IGNORE perfume_notes SET note_id=? WHERE note_id=?')->execute([$target,$source]);$this->db->prepare('DELETE FROM perfume_notes WHERE note_id=?')->execute([$source]);}elseif($this->type==='tag'){$this->db->prepare('UPDATE IGNORE perfume_tags SET tag_id=? WHERE tag_id=?')->execute([$target,$source]);$this->db->prepare('DELETE FROM perfume_tags WHERE tag_id=?')->execute([$source]);}$this->softDelete($source);}
}
